import { Injectable } from '@nestjs/common';
import { CICDConfig } from '../interfaces/config.interface';

@Injectable()
export class DashboardService {
  generateDeploymentDashboard(config: CICDConfig): string {
    const { project, cloud, notifications, jenkinsConfig } = config;

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Deployment Dashboard - ${project.projectName}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 20px; background-color: #f4f7f6; }
        .container { background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #2980b9; margin-top: 30px; }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
        .card { background: #f9f9f9; padding: 20px; border-radius: 6px; border-left: 4px solid #3498db; }
        .card h3 { margin-top: 0; color: #34495e; }
        .status { display: inline-block; padding: 5px 12px; border-radius: 20px; font-size: 0.85em; font-weight: bold; text-transform: uppercase; }
        .status-active { background: #e8f5e9; color: #2e7d32; }
        ul { padding-left: 20px; }
        code { background: #eee; padding: 2px 5px; border-radius: 4px; font-family: 'Courier New', Courier, monospace; }
        .footer { margin-top: 50px; text-align: center; font-size: 0.9em; color: #7f8c8d; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 Deployment Dashboard: ${project.projectName}</h1>
        <p>Generated by Jenkins-Generator v2.1.0</p>

        <div class="grid">
            <div class="card">
                <h3>📦 Project Info</h3>
                <ul>
                    <li><strong>Type:</strong> ${project.projectType}</li>
                    <li><strong>Language:</strong> ${project.language}</li>
                    <li><strong>Repository:</strong> <code>${
                      project.repository
                    }</code></li>
                    <li><strong>Branch:</strong> <code>${
                      project.branch
                    }</code></li>
                </ul>
            </div>

            <div class="card">
                <h3>☁️ Cloud Deployment</h3>
                <ul>
                    <li><strong>Provider:</strong> ${cloud.provider.toUpperCase()}</li>
                    <li><strong>Region:</strong> ${cloud.region}</li>
                    <li><strong>Tier:</strong> ${
                      cloud.deploymentConfig.tier
                    }</li>
                    <li><strong>Strategy:</strong> ${
                      cloud.deploymentConfig.deploymentStrategy
                    }</li>
                    <li><strong>Port:</strong> ${
                      cloud.deploymentConfig.port
                    }</li>
                </ul>
            </div>

            <div class="card">
                <h3>⚙️ Resources</h3>
                <ul>
                    <li><strong>Instance:</strong> ${cloud.instanceType}</li>
                    <li><strong>Auto-Scaling:</strong> ${
                      cloud.deploymentConfig.autoScaling
                        ? 'Enabled'
                        : 'Disabled'
                    }</li>
                    <li><strong>Min/Max:</strong> ${
                      cloud.deploymentConfig.minInstances || 1
                    } / ${cloud.deploymentConfig.maxInstances || 1}</li>
                    <li><strong>Load Balancer:</strong> ${
                      cloud.deploymentConfig.useLoadBalancer
                        ? 'Configured'
                        : 'None'
                    }</li>
                </ul>
            </div>

            <div class="card">
                <h3>🔔 Notifications</h3>
                <ul>
                    <li><strong>Email:</strong> ${notifications.email}</li>
                    <li><strong>Platforms:</strong> ${
                      notifications.platforms.map((p) => p.type).join(', ') ||
                      'None'
                    }</li>
                </ul>
            </div>
        </div>

        <h2>🛠️ Infrastructure as Code (IaC)</h2>
        <p>Terraform modules have been generated in <code>.cicd/terraform/</code> to manage your ${cloud.provider.toUpperCase()} resources.</p>

        <div class="footer">
            &copy; 2026 Jenkins-Generator. Empowering your CI/CD journey.
        </div>
    </div>
</body>
</html>
`;
  }
}
